### ISSUE TITLE
调用vxios.uploadFile时，提示request:fail method is invalid

### ISSUE THREAD

**Issue by HuangYaobin** [GAtomis/Vxios#1]
调用
```js
vxios.uploadFile(
  "https://xxxx.com/api/photo/upload", 
  { filePath }
)
```
结果
```js
{errMsg: "request:fail invalid url "/photo/wxupload""}
```

**Comment by GAtomis** [comment]
ok收到

**Comment by GAtomis** [comment]
裂开大小写原因,已修复等待下一次提交
![微信截图_20220303174353](https://user-images.githubusercontent.com/40788938/156539511-8a9d93d3-d35e-4473-a477-119e8434961d.png)

`wx.chooseMedia({
      count: 9,
      mediaType: ['image', 'video'],
      sourceType: ['album', 'camera'],
      maxDuration: 30,
      camera: 'back',
      success(res) {
        console.log(res.tempFiles[0].tempFilePath)
        myVxios.uploadFile("oss/file/upload", {
          filePath: res.tempFiles[0].tempFilePath,
          name: 'file',
          formData: {
            app: 'xxx',
          },
          header: {
            'Content-Type': 'multipart/form-data',
          },
        }).then(res=>{

          console.log(res);
        })
      }
    })`

**Comment by GAtomis** [comment]
已修复请更新至1.0.1-beta.35 感谢你的issues

**Comment by GAtomis** [comment]
> 调用
> 
> ```js
> vxios.uploadFile(
>   "https://xxxx.com/api/photo/upload", 
>   { filePath }
> )
> ```
> 
> 结果
> 
> ```js
> {errMsg: "request:fail invalid url "/photo/wxupload""}
> ```
